// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-BT9s1_rUNeTOvAMF5W1g6TDI8dVq7I',
    appId: '1:63690546236:web:69b17c19c4d406eeeef739',
    messagingSenderId: '63690546236',
    projectId: 'mobile-app-teamproject',
    authDomain: 'mobile-app-teamproject.firebaseapp.com',
    storageBucket: 'mobile-app-teamproject.appspot.com',
    measurementId: 'G-E079BBWNPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnk45ZwlYTOBYT7plmzs_RGeIQuflCe78',
    appId: '1:63690546236:android:73182e2055aa7025eef739',
    messagingSenderId: '63690546236',
    projectId: 'mobile-app-teamproject',
    storageBucket: 'mobile-app-teamproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgRtWLmbowwGVm3AVmKa_pC3TRZYQ5CZ4',
    appId: '1:63690546236:ios:1f0b0d24ebff3f4aeef739',
    messagingSenderId: '63690546236',
    projectId: 'mobile-app-teamproject',
    storageBucket: 'mobile-app-teamproject.appspot.com',
    iosClientId: '63690546236-5d3kn5suj1o8ohnht2qhe0vb68mbnh38.apps.googleusercontent.com',
    iosBundleId: 'com.example.w3Class',
  );
}
